### ISSUE TITLE
打包不成功

### ISSUE THREAD

**Issue by heppytt** [Jasonandy/Skeleton-X#1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project skeleton-crawler: Compilation failure: Compilation failure: 
[ERROR] /Users/sunhongjie/ideaspace/Skeleton-X-master/skeleton-crawler/src/main/java/cn/ucaner/skeleton/crawler/crawlers/DefaultRedisQueueEG.java:[20,60] 程序包cn.ucaner.skeleton.service.framework.common.base.dao不存在
[ERROR] /Users/sunhongjie/ideaspace/Skeleton-X-master/skeleton-crawler/src/main/java/cn/ucaner/skeleton/crawler/crawlers/DefaultRedisQueueEG.java:[50,5] 找不到符号
[ERROR]   符号:   类 ElasticSearchBaseDao
[ERROR]   位置: 类 cn.ucaner.skeleton.crawler.crawlers.DefaultRedisQueueEG
[ERROR] /Users/sunhongjie/ideaspace/Skeleton-X-master/skeleton-crawler/src/main/java/cn/ucaner/skeleton/crawler/crawlers/CnblogCrawler.java:[20,60] 程序包cn.ucaner.skeleton.service.framework.common.base.dao不存在
[ERROR] /Users/sunhongjie/ideaspace/Skeleton-X-master/skeleton-crawler/src/main/java/cn/ucaner/skeleton/crawler/crawlers/CnblogCrawler.java:[46,5] 找不到符号
[ERROR]   符号:   类 ElasticSearchBaseDao
[ERROR]   位置: 类 cn.ucaner.skeleton.crawler.crawlers.CnblogCrawler
[ERROR] /Users/sunhongjie/ideaspace/Skeleton-X-master/skeleton-crawler/src/main/java/cn/ucaner/skeleton/crawler/webmagic/kafka/consumer/HupuKafkaConsumer.java:[18,50] 程序包cn.ucaner.skeleton.service.kafka.constants不存在
[ERROR] /Users/sunhongjie/ideaspace/Skeleton-X-master/skeleton-crawler/src/main/java/cn/ucaner/skeleton/crawler/webmagic/kafka/consumer/HupuKafkaConsumer.java:[42,29] 找不到符号
[ERROR]   符号:   变量 KafkaConstant
[ERROR]   位置: 类 cn.ucaner.skeleton.crawler.webmagic.kafka.consumer.HupuKafkaConsumer
[ERROR] -> [Help 1]
[ERROR]

**Comment by Jasonandy** [comment]
![image](https://user-images.githubusercontent.com/12879147/58310658-bc5da480-7e39-11e9-9d13-f4b25abc5667.png)
爬虫模块需要配置es 和 kafka

**Comment by Jasonandy** [comment]
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project skeleton-crawler: Compilation failure: Compilation failure:
> [ERROR] /Users/sunhongjie/ideaspace/Skeleton-X-master/skeleton-crawler/src/main/java/cn/ucaner/skeleton/crawler/crawlers/DefaultRedisQueueEG.java:[20,60] 程序包cn.ucaner.skeleton.service.framework.common.base.dao不存在
> [ERROR] /Users/sunhongjie/ideaspace/Skeleton-X-master/skeleton-crawler/src/main/java/cn/ucaner/skeleton/crawler/crawlers/DefaultRedisQueueEG.java:[50,5] 找不到符号
> [ERROR] 符号: 类 ElasticSearchBaseDao
> [ERROR] 位置: 类 cn.ucaner.skeleton.crawler.crawlers.DefaultRedisQueueEG
> [ERROR] /Users/sunhongjie/ideaspace/Skeleton-X-master/skeleton-crawler/src/main/java/cn/ucaner/skeleton/crawler/crawlers/CnblogCrawler.java:[20,60] 程序包cn.ucaner.skeleton.service.framework.common.base.dao不存在
> [ERROR] /Users/sunhongjie/ideaspace/Skeleton-X-master/skeleton-crawler/src/main/java/cn/ucaner/skeleton/crawler/crawlers/CnblogCrawler.java:[46,5] 找不到符号
> [ERROR] 符号: 类 ElasticSearchBaseDao
> [ERROR] 位置: 类 cn.ucaner.skeleton.crawler.crawlers.CnblogCrawler
> [ERROR] /Users/sunhongjie/ideaspace/Skeleton-X-master/skeleton-crawler/src/main/java/cn/ucaner/skeleton/crawler/webmagic/kafka/consumer/HupuKafkaConsumer.java:[18,50] 程序包cn.ucaner.skeleton.service.kafka.constants不存在
> [ERROR] /Users/sunhongjie/ideaspace/Skeleton-X-master/skeleton-crawler/src/main/java/cn/ucaner/skeleton/crawler/webmagic/kafka/consumer/HupuKafkaConsumer.java:[42,29] 找不到符号
> [ERROR] 符号: 变量 KafkaConstant
> [ERROR] 位置: 类 cn.ucaner.skeleton.crawler.webmagic.kafka.consumer.HupuKafkaConsumer
> [ERROR] -> [Help 1]
> [ERROR]

需要把install common模块 和service模块 这个crawler爬虫模块是依赖前两个模块的
